# -*- coding: utf-8 -*-
"""
report_generator.py - Auto Report Generator (merged from V1 Zhuque)
Part of Wuxing Flywheel 2.0

Takes complete pipeline results (all 5 phases + CG) and generates:
1. Structured Markdown report
2. Interactive HTML dashboard (SpaceX aesthetic)
3. JSON summary for API consumption
"""
import json, time, hashlib, os, re

VERSION = "2.0.0"

try:
    from wuxing_pipeline_v2 import call_llm, PHASE_MODEL, _strip_code_fences
    LLM = True
except:
    LLM = False


def generate_markdown_report(pipeline_result):
    """Generate structured Markdown report from pipeline results."""
    topic = pipeline_result.get("topic", "Unknown")
    phases = pipeline_result.get("phases", {})
    cg = pipeline_result.get("cognitive_graph", {})

    wood = phases.get("wood", {})
    fire = phases.get("fire", {})
    earth = phases.get("earth", {})
    metal = phases.get("metal", {})
    water = phases.get("water", {})

    seeds = wood.get("seeds", [])
    analysis = fire.get("analysis", "")
    synthesis = earth.get("synthesis", {})
    dims = metal.get("dimensions", {})
    agent_eval = metal.get("agent_eval", {})
    new_seeds = water.get("new_seeds", [])

    context = "Topic: {}\n\nWOOD SEEDS ({}):\n{}\n\nFIRE ANALYSIS ({} chars):\n{}\n\nEARTH SYNTHESIS:\nSummary: {}\nFindings: {}\nRecommendations: {}\nData Gaps: {}\n\nMETAL VALIDATION:\nVerdict: {} (Score: {:.2f})\nDimensions: {}\nAgent Grade: {}/{} ({}/10)\n\nCOGNITIVE GRAPH:\nResiduals: {}, Patterns: {}\nPath Weights: {}\nEvolution: {}\n\nWATER SEEDS ({}):\n{}".format(
        topic,
        len(seeds),
        json.dumps([s.get('angle','') for s in seeds[:5]], ensure_ascii=False, indent=2),
        len(analysis),
        analysis[:1500],
        synthesis.get('executive_summary', 'N/A'),
        json.dumps(synthesis.get('key_findings', [])[:5], ensure_ascii=False),
        json.dumps(synthesis.get('recommendations', [])[:5], ensure_ascii=False),
        json.dumps(synthesis.get('data_gaps', [])[:5], ensure_ascii=False),
        metal.get('verdict', 'N/A'),
        metal.get('composite_score', 0),
        json.dumps(dims, indent=2),
        agent_eval.get('grade', 'N/A'),
        agent_eval.get('grade_label', 'N/A'),
        agent_eval.get('overall_score', 0),
        cg.get('residuals', 0),
        cg.get('patterns', 0),
        json.dumps(cg.get('path_weights', {}).get('updated', {}), indent=2),
        json.dumps(cg.get('evolution', {}).get('lessons_learned', []), ensure_ascii=False),
        len(new_seeds),
        json.dumps([s.get('angle','')[:80] for s in new_seeds[:5]], ensure_ascii=False),
    )

    verdict_str = metal.get('verdict', '?')
    score_str = "{:.2f}".format(metal.get('composite_score', 0))
    grade_str = agent_eval.get('grade', '?')
    ts_str = time.strftime('%Y-%m-%d %H:%M')

    prompt = (
        "You are the Zhuque Report Engine of SkyCetus. Generate a comprehensive research report.\n\n"
        + context + "\n\n"
        "Generate a Markdown report with this structure:\n"
        "# [topic] - Wuxing Analysis Report\n\n"
        "## Executive Summary\n"
        "(3 sentences: core finding, market insight, strategic implication)\n\n"
        "## Key Findings\n"
        "(5-7 bullet points, each with data support)\n\n"
        "## Deep Analysis\n"
        "### Market Landscape\n"
        "### Technology Trends\n"
        "### Competition\n\n"
        "## Risk Assessment\n"
        "(3-4 risks with severity and mitigation)\n\n"
        "## Strategic Recommendations\n"
        "(3-5 actionable recommendations with priority P0/P1/P2)\n\n"
        "## Cognitive Evolution\n"
        "(Patterns, path weight shifts, residuals from cognitive graph)\n\n"
        "## Next Research Directions\n"
        "(Water seeds for next cycle)\n\n"
        "---\n"
        "*Generated by LongZhu Engine Wuxing Pipeline v4.1 | Metal: " + verdict_str + " (" + score_str + ") | Grade: " + grade_str + " | " + ts_str + "*\n\n"
        "Requirements:\n"
        "- Write in Chinese for maximum impact\n"
        "- Include specific numbers and data points\n"
        "- Keep total length 1500-2500 chars\n"
        "- Be actionable and decision-ready\n"
        "- Output ONLY Markdown, no code fences"
    )

    if LLM:
        result = call_llm(prompt, model="minimax", timeout=60, thinking_budget=500)
        if result:
            if result.strip().startswith('```'):
                lines = result.strip().split('\n')
                if lines[0].startswith('```'):
                    lines = lines[1:]
                if lines and lines[-1].strip() == '```':
                    lines = lines[:-1]
                result = '\n'.join(lines)
            return result

    return _fallback_markdown(topic, synthesis, metal, agent_eval, cg, new_seeds)


def _fallback_markdown(topic, synthesis, metal, agent_eval, cg, new_seeds):
    """Fallback Markdown when LLM is unavailable."""
    findings = synthesis.get("key_findings", [])
    recs = synthesis.get("recommendations", [])

    md = "# {} - Wuxing Analysis Report\n\n".format(topic)
    md += "## Executive Summary\n{}\n\n".format(synthesis.get('executive_summary', 'Analysis pending.'))

    md += "## Key Findings\n"
    for f in findings[:7]:
        if isinstance(f, dict):
            md += "- **[{}]** {}\n".format(f.get('confidence','?'), f.get('finding',''))
        else:
            md += "- {}\n".format(f)

    md += "\n## Validation\n"
    md += "- **Metal**: {} (Score: {:.2f})\n".format(metal.get('verdict',''), metal.get('composite_score',0))
    md += "- **Agent Grade**: {} ({}/10)\n".format(agent_eval.get('grade','?'), agent_eval.get('overall_score',0))

    md += "\n## Recommendations\n"
    for r in recs[:5]:
        if isinstance(r, dict):
            md += "- **[{}]** {}\n".format(r.get('priority','?'), r.get('action',''))
        else:
            md += "- {}\n".format(r)

    md += "\n## Next Research Directions\n"
    for s in new_seeds[:5]:
        md += "- [{}] {}\n".format(s.get('priority','?'), s.get('angle','')[:100])

    md += "\n---\n*LongZhu Engine | {}*\n".format(time.strftime('%Y-%m-%d %H:%M'))
    return md


def generate_html_report(topic, markdown_report, pipeline_result):
    """Generate interactive HTML dashboard."""
    metal = pipeline_result.get("phases", {}).get("metal", {})
    agent_eval = metal.get("agent_eval", {})
    cg = pipeline_result.get("cognitive_graph", {})
    dims = metal.get("dimensions", {})
    elapsed = pipeline_result.get("total_elapsed", 0)
    lux = pipeline_result.get("lux_distribution", {})
    total_lux = lux.get("total_lux", lux.get("total_distributed", 0)) if lux else 0

    NL = chr(10)

    # Build dimension bars
    dim_bars = ""
    for k, v in dims.items():
        pct = int(v * 100) if isinstance(v, (int, float)) else 50
        color = "#22c55e" if pct >= 70 else "#eab308" if pct >= 40 else "#ef4444"
        label = k.replace("_", " ").title()
        dim_bars += '<div class="dim-row"><span class="dim-label">{}</span><div class="dim-bar"><div class="dim-fill" style="width:{}%;background:{}"></div></div><span class="dim-val">{}%</span></div>{}'.format(label, pct, color, pct, NL)

    # Agent scores
    agent_cards = ""
    for a in agent_eval.get("agents", []):
        score = a.get("score", 0)
        color = "#22c55e" if score >= 7 else "#eab308" if score >= 5 else "#ef4444"
        name = a.get("agent", "?").title()
        agent_cards += '<div class="agent-card"><div class="agent-name">{}</div><div class="agent-score" style="color:{}">{}</div></div>{}'.format(name, color, score, NL)

    # Path weights
    pw = cg.get("path_weights", {}).get("updated", {})
    pw_a = pw.get("A", 65)
    pw_b = pw.get("B", 25)
    pw_c = pw.get("C", 10)

    verdict = metal.get("verdict", "?")
    verdict_color = "#22c55e" if verdict == "PASS" else "#eab308" if verdict == "CONDITIONAL" else "#ef4444"
    grade = agent_eval.get("grade", "?")
    grade_color = "#22c55e" if grade in ("S","A") else "#eab308" if grade == "B" else "#ef4444"

    # Convert markdown to simple HTML
    report_html = markdown_report
    report_html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', report_html, flags=re.MULTILINE)
    report_html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', report_html, flags=re.MULTILINE)
    report_html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', report_html, flags=re.MULTILINE)
    report_html = re.sub(r'^\- \*\*(.+?)\*\*(.*)$', r'<li><strong>\1</strong>\2</li>', report_html, flags=re.MULTILINE)
    report_html = re.sub(r'^\- (.+)$', r'<li>\1</li>', report_html, flags=re.MULTILINE)
    report_html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', report_html)
    report_html = report_html.replace('\n\n', '<br><br>')

    version_str = pipeline_result.get('pipeline_version', '?')
    ts_str = time.strftime('%Y-%m-%d %H:%M')

    css = """*{margin:0;padding:0;box-sizing:border-box}
body{background:#0a0e1a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;line-height:1.6}
.container{max-width:1100px;margin:0 auto;padding:2rem}
nav{display:flex;justify-content:space-between;align-items:center;padding:1rem 2rem;border-bottom:1px solid rgba(255,255,255,0.1)}
nav a{color:#94a3b8;text-decoration:none;margin:0 1rem;font-size:0.9rem}
nav a:hover{color:#38bdf8}
.brand{font-size:1.1rem;font-weight:700;background:linear-gradient(135deg,#38bdf8,#22c55e);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero{text-align:center;padding:3rem 0 2rem}
.hero h1{font-size:2rem;background:linear-gradient(135deg,#38bdf8,#a78bfa,#22c55e);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:0.5rem}
.hero .subtitle{color:#94a3b8;font-size:0.95rem}
.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin:2rem 0}
.stat-card{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:1.2rem;text-align:center}
.stat-val{font-size:1.8rem;font-weight:700;margin-bottom:0.3rem}
.stat-label{color:#94a3b8;font-size:0.8rem;text-transform:uppercase}
.section{background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:2rem;margin:1.5rem 0}
.section h2{color:#38bdf8;margin-bottom:1rem;font-size:1.3rem}
.dim-row{display:flex;align-items:center;margin:0.5rem 0}
.dim-label{width:140px;font-size:0.85rem;color:#94a3b8}
.dim-bar{flex:1;height:8px;background:rgba(255,255,255,0.1);border-radius:4px;margin:0 0.8rem;overflow:hidden}
.dim-fill{height:100%;border-radius:4px;transition:width 0.5s}
.dim-val{width:45px;text-align:right;font-size:0.85rem;font-weight:600}
.agents-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin:1rem 0}
.agent-card{background:rgba(255,255,255,0.05);border-radius:10px;padding:1rem;text-align:center}
.agent-name{color:#94a3b8;font-size:0.8rem;text-transform:uppercase;margin-bottom:0.3rem}
.agent-score{font-size:2rem;font-weight:700}
.path-weights{display:flex;gap:1rem;margin:1rem 0}
.pw-item{flex:1;background:rgba(255,255,255,0.05);border-radius:10px;padding:1rem;text-align:center}
.pw-val{font-size:1.5rem;font-weight:700;color:#38bdf8}
.pw-label{color:#94a3b8;font-size:0.75rem;margin-top:0.3rem}
.report-content{line-height:1.8}
.report-content h1{font-size:1.5rem;color:#38bdf8;margin:1.5rem 0 0.8rem;border-bottom:1px solid rgba(255,255,255,0.1);padding-bottom:0.5rem}
.report-content h2{font-size:1.2rem;color:#a78bfa;margin:1.2rem 0 0.6rem}
.report-content h3{font-size:1.05rem;color:#22c55e;margin:1rem 0 0.5rem}
.report-content li{margin:0.4rem 0;padding-left:0.5rem;list-style:none}
.report-content li:before{content:">>> ";color:#38bdf8}
.report-content strong{color:#f1f5f9}
footer{text-align:center;padding:3rem 0 2rem;color:#475569;font-size:0.85rem;border-top:1px solid rgba(255,255,255,0.05);margin-top:3rem}
@media(max-width:768px){.stats-grid,.agents-grid{grid-template-columns:repeat(2,1fr)}.path-weights{flex-direction:column}}"""

    html = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s - LongZhu Analysis Report</title>
<style>
%s
</style>
</head>
<body>
<nav>
<span class="brand">LongZhu Engine</span>
<div>
<a href="/">Home</a>
<a href="/flywheel-live.html">Flywheel</a>
<a href="/thoughts.html">Thoughts</a>
<a href="/finance.html">Finance</a>
</div>
</nav>
<div class="container">
<div class="hero">
<h1>%s</h1>
<p class="subtitle">Wuxing Flywheel Analysis - Pipeline v4.1 - %s</p>
</div>
<div class="stats-grid">
<div class="stat-card"><div class="stat-val" style="color:%s">%s</div><div class="stat-label">Metal Verdict</div></div>
<div class="stat-card"><div class="stat-val" style="color:%s">%s</div><div class="stat-label">Agent Grade</div></div>
<div class="stat-card"><div class="stat-val" style="color:#a78bfa">%s</div><div class="stat-label">CG Residuals</div></div>
<div class="stat-card"><div class="stat-val" style="color:#22c55e">%.0f</div><div class="stat-label">Lux Earned</div></div>
</div>
<div class="section"><h2>Metal 8-Dimension Validation</h2>%s</div>
<div class="section"><h2>Multi-Agent Evaluation (%.1f/10)</h2><div class="agents-grid">%s</div></div>
<div class="section"><h2>Cognitive Graph Path Weights</h2>
<div class="path-weights">
<div class="pw-item"><div class="pw-val">%.1f%%</div><div class="pw-label">A - Exploitation</div></div>
<div class="pw-item"><div class="pw-val">%.1f%%</div><div class="pw-label">B - Adjacent</div></div>
<div class="pw-item"><div class="pw-val">%.1f%%</div><div class="pw-label">C - Paradigm</div></div>
</div></div>
<div class="section"><h2>Analysis Report</h2><div class="report-content">%s</div></div>
</div>
<footer>SkyCetus - LongZhu Engine - Pipeline %s - %.1fs</footer>
</body>
</html>""" % (
        topic, css, topic, ts_str,
        verdict_color, verdict,
        grade_color, grade,
        cg.get('residuals', 0),
        total_lux,
        dim_bars,
        agent_eval.get('overall_score', 0),
        agent_cards,
        pw_a, pw_b, pw_c,
        report_html,
        version_str, elapsed
    )

    return html


def generate_report(pipeline_result, deploy=False, deploy_path=None):
    """Full report generation pipeline."""
    topic = pipeline_result.get("topic", "Unknown")
    t0 = time.time()

    print("[Zhuque] Generating Markdown report...")
    markdown = generate_markdown_report(pipeline_result)
    t_md = time.time() - t0
    print("[Zhuque] Markdown: {} chars ({:.1f}s)".format(len(markdown), t_md))

    t1 = time.time()
    html = generate_html_report(topic, markdown, pipeline_result)
    t_html = time.time() - t1
    print("[Zhuque] HTML: {} chars ({:.1f}s)".format(len(html), t_html))

    metal = pipeline_result.get("phases", {}).get("metal", {})
    agent_eval = metal.get("agent_eval", {})
    cg = pipeline_result.get("cognitive_graph", {})

    json_summary = {
        "topic": topic,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S+08:00"),
        "pipeline_version": pipeline_result.get("pipeline_version", "?"),
        "total_elapsed": pipeline_result.get("total_elapsed", 0),
        "metal_verdict": metal.get("verdict", "?"),
        "metal_score": metal.get("composite_score", 0),
        "agent_grade": agent_eval.get("grade", "?"),
        "agent_score": agent_eval.get("overall_score", 0),
        "cg_residuals": cg.get("residuals", 0),
        "cg_patterns": cg.get("patterns", 0),
        "water_seeds": len(pipeline_result.get("phases", {}).get("water", {}).get("new_seeds", [])),
        "lux": pipeline_result.get("lux_distribution", {}).get("total_lux", 0),
    }

    report_dir = deploy_path or r"D:\ClawMatrix\reports"
    os.makedirs(report_dir, exist_ok=True)

    slug = re.sub(r'[^a-z0-9]+', '-', topic.lower())[:40].strip('-')
    ts = time.strftime("%Y%m%d_%H%M")

    md_path = os.path.join(report_dir, "{}_{}.md".format(slug, ts))
    html_path = os.path.join(report_dir, "{}_{}.html".format(slug, ts))
    json_path = os.path.join(report_dir, "{}_{}.json".format(slug, ts))

    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(markdown)
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html)
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(json_summary, f, ensure_ascii=False, indent=2)

    total = time.time() - t0
    print("[Zhuque] Reports saved to {}/ ({:.1f}s total)".format(report_dir, total))

    return {
        "markdown": markdown,
        "html_length": len(html),
        "json_summary": json_summary,
        "files": {"md": md_path, "html": html_path, "json": json_path},
        "timing": {"markdown": t_md, "html": t_html, "total": total},
    }


def self_test():
    """Self-test with mock pipeline result."""
    print("report_generator.py v{}".format(VERSION))

    mock = {
        "topic": "SiC Power Semiconductor Market 2026",
        "pipeline_version": "4.1.0-multi-agent-metal",
        "total_elapsed": 105.0,
        "phases": {
            "wood": {"seeds": [{"angle": "Market size"}, {"angle": "Key players"}]},
            "fire": {"analysis": "The SiC market is projected to reach $12B by 2026. Key players include Wolfspeed, STMicro, and Infineon. CAGR of 25% driven by EV adoption."},
            "earth": {"synthesis": {
                "executive_summary": "SiC is the leading wide-bandgap semiconductor for power applications.",
                "key_findings": [{"finding": "Market CAGR 25%", "confidence": "high"}],
                "recommendations": [{"action": "Focus on 8-inch wafer transition", "priority": "P0"}],
                "data_gaps": ["Emerging competitors data missing"],
                "residual_questions": ["What about GaN competition?"],
                "synthesis_quality": {"seed_coverage": 0.85, "analysis_grounding": 0.9, "actionability": 0.8},
            }},
            "metal": {
                "verdict": "PASS", "composite_score": 0.72,
                "dimensions": {"data_completeness": 0.8, "coverage_breadth": 0.7, "analysis_depth": 0.9, "multi_agent": 0.75},
                "agent_eval": {
                    "grade": "A", "grade_label": "Excellent", "overall_score": 7.5,
                    "agents": [
                        {"agent": "quality", "score": 8.0},
                        {"agent": "risk", "score": 7.0},
                        {"agent": "innovation", "score": 7.5},
                        {"agent": "integration", "score": 7.5},
                    ]
                },
            },
            "water": {"new_seeds": [{"angle": "GaN vs SiC cost comparison", "priority": "high"}]},
        },
        "cognitive_graph": {
            "residuals": 8, "patterns": 2,
            "path_weights": {"updated": {"A": 55, "B": 30, "C": 15}},
            "evolution": {"lessons_learned": ["Data gaps are persistent"]},
        },
        "lux_distribution": {"total_lux": 80.0},
    }

    result = generate_report(mock)
    print("  Markdown: {} chars".format(len(result['markdown'])))
    print("  HTML: {} chars".format(result['html_length']))
    print("  Files: {}".format(list(result['files'].values())))
    print("  PASS")
    return True


if __name__ == "__main__":
    self_test()
